services:
  platform-agent:
    build: ./agents/default
    environment:
      - AGENT_NAME=Platform Agent
      - AGENT_DESCRIPTION=Handles queries related to the internal development platform
      - AGENT_SYSTEM_PROMPT="You are a helpful platform engineer who can answer questions about your companies internal developer platform"
      - AGENT_SERVER__HOST=0.0.0.0
      - AGENT_SERVER__URL="http://supervisor-agent:9000"
      - AGENT_A2A__PEER_AGENTS=["http://aws-agent:9000","http://terraform-agent:9000"]
    ports:
      - "9000:9000"
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9000/health || exit 1']
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  aws-agent:
    build: ./agents/default
    environment:
      - AGENT_NAME=AWS Agent
      - AGENT_DESCRIPTION=Agent for answering AWS questions
      - AGENT_SYSTEM_PROMPT="You are a helpful platform engineer who can specifically answer questions about your companies internal developer platform related to Amazon Web Services"
      - AGENT_SERVER__HOST=0.0.0.0
      - AGENT_SERVER__URL="http://aws-agent:9000"
      - AGENT_MCP_SERVERS=[{name='AWS Knowledge', url='https://knowledge-mcp.global.api.aws'}]
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9000/health || exit 1']
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  terraform-agent:
    build: ./agents/default
    environment:
      - AGENT_NAME=Terraform Agent
      - AGENT_DESCRIPTION=Agent for answering questions about Terraform code, providers and modules
      - AGENT_SYSTEM_PROMPT="You are a helpful platform engineer who can specifically answer questions about Terraform code, providers and modules."
      - AGENT_SERVER__HOST=0.0.0.0
      - AGENT_SERVER__URL="http://terraform-agent:9000"
      - AGENT_MCP_SERVERS=[{name='Wiki', url='http://terraform-mcp:8080/mcp'}]
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9000/health || exit 1']
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  terraform-mcp:
    image: hashicorp/terraform-mcp-server:0.3.2
    environment:
      - TRANSPORT_MODE=streamable-http
      - TRANSPORT_HOST=0.0.0.0
    restart: unless-stopped