{{- range $agentId, $agent := .Values.agents }}
{{- $agentWithId := merge (dict "id" $agentId) $agent }}
{{- $ctx := dict "root" $ "agent" $agentWithId }}
{{- $config := mustMergeOverwrite (deepCopy $.Values.agentDefaults) (omit $agentWithId "name" "description" "system_prompt") }}
{{- if $config.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $config.secret.name | default (include "platform-ai.agentFullname" $ctx) }}
  labels:
    {{- include "platform-ai.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $agentId }}
  {{- with $config.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if $config.auth }}
  {{- if eq $config.auth.mode "bearer" }}
  AGENT_AUTH__BEARER__TOKEN: {{ $config.auth.bearer.token | b64enc | quote }}
  {{- else if eq $config.auth.mode "oidc" }}
  AGENT_AUTH__OIDC__CLIENT_SECRET: {{ $config.auth.oidc.client_secret | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if ne $.Values.agentDefaults.opentelemetry.endpoint "" }}
  OTEL_EXPORTER_OTLP_HEADERS: {{ (printf "Authorization=Basic %s" ($.Values.agentDefaults.opentelemetry.token | b64enc) )| b64enc }}
  {{- end }}
  {{- range $key, $value := $config.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}