{{- range .Values.mcpServers }}
{{- $mcpServer := . }}
{{- $ctx := dict "root" $ "mcpServer" $mcpServer }}
{{- if $mcpServer.serviceAccount }}
{{- if $mcpServer.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform-ai.mcpServerFullname" $ctx }}
  labels:
    {{- include "platform-ai.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $mcpServer.id }}
  {{- with $mcpServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $mcpServer.serviceAccount.automount | default true }}
{{- end }}
{{- end }}
{{- end }}
