{{- range .Values.mcpServers }}
{{- $mcpServer := . }}
{{- $ctx := dict "root" $ "mcpServer" $mcpServer }}
{{- $mcpEnv := $mcpServer.env | default dict }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform-ai.mcpServerFullname" $ctx }}
  labels:
    {{- include "platform-ai.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $mcpServer.id }}
data:
  {{- range $key, $value := $mcpEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
