{{- if and .Values.slackBot.enabled .Values.slackBot.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform-ai.slackBotFullname" . }}
  labels:
    {{- include "platform-ai.labels" . | nindent 4 }}
    app.kubernetes.io/type: slack-bot
  {{- with .Values.slackBot.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.slackBot.serviceAccount.automount }}
{{- end }}
