image:
  repository: "ghcr.io/niallthomson/ai-platform-engineering-experiment"
  pullPolicy: IfNotPresent
  tag: "latest"

mcpServers:
  - id: "terraform"
    image:
      repository: hashicorp/terraform-mcp-server
      tag: "0.3.2"
      pullPolicy: IfNotPresent
    service:
      port: 8080
    env:
      TRANSPORT_MODE: "streamable-http"
      TRANSPORT_HOST: "0.0.0.0"

agents:
  platform:
    name: "Platform Agent"
    description: |
      Handles queries related to the internal development platform
    system_prompt: |
      You are a helpful platform engineer who can answer questions about your companies internal developer platform
    a2a:
      peerAgents:
        - aws
        - terraform
          
  aws:
    name: "AWS Agent"
    description: |
      Agent for answering AWS questions
    system_prompt: |
      You are a helpful platform engineer who can specifically answer questions about your companies internal developer platform related to Amazon Web Services
    mcpServers:
      - name: "AWS Knowledge"
        url: "https://knowledge-mcp.global.api.aws"

  terraform:
    name: "Terraform Agent"
    description: |
      Agent for answering questions about Terraform code, providers and modules
    system_prompt: |
      You are a helpful platform engineer who can specifically answer questions about Terraform code, providers and modules.
    mcpServers:
      - name: "Wiki"
        id: terraform
        path: "/mcp"
